server:
  port: 9001
   
spring:
  application:
    name: SERVICE-ONE-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:databasename
    

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone : http://localhost:8761/eureka/
#      instance :
#        hostname : localhost    
